name: preacher_helper
description: Preacher Helper.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0-259.8.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.16.0
  firebase_auth: ^0.20.0+1
  flamingo: ^1.15.3
  flamingo_annotation: ^0.4.0
  fluro: ^1.7.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1
  flutter_launcher_icons: ^0.8.1
  flamingo_generator: ^0.8.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.jpg"
flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Barlow Condensed
      fonts:
        - asset: assets/fonts/BarlowCondensed-Regular.ttf
        - asset: assets/fonts/BarlowCondensed-SemiBold.ttf
        - asset: assets/fonts/BarlowCondensed-Bold.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: Playfair Display
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay-SemiBold.ttf
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
